/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
int main(void)
 {

	char str[10];


	LcdInit();
UartInit(9600);
	while(1){

     UartGets(str);

     strupr(str);
     if(str[0]=='L' && str[1]=='1')
     LcdPuts(LCD_LINE1,str+2);
     else
    	 LcdPuts(LCD_LINE2,str);
     DelayMs(10);
     while(1){

     LcdWriteByte(LCD_CMD, LCD_SHIFT);
          DelayMs(1000);
     }

	}


return 0;

}





