/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "accel.h"
#include "lcd.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

		uint8_t leds[] = {LED_GREEN, LED_ORANGE, LED_RED, LED_BLUE};
	for(int i=0;i<4;i++)
		led_init(LED_GREEN+i);

	char str[32];
	AccelData_t accel;
	LcdInit();
	AccelInit();
	while(AccelWaitForChange()) {
		AccelRead(&accel);
		sprintf(str, "X=%d,Y=%d ", accel.x, accel.y);
		LcdPuts(LCD_LINE1, str);

		LcdPuts(LCD_LINE2, str);
		if(accel.x >=3000)
			led_on(LED_RED);
		else
			led_off(LED_RED);
		if(accel.x<=-3000)
			led_on(LED_GREEN);
		else
			led_off(LED_GREEN);
		if(accel.y>=3000)
			led_on(LED_ORANGE);
		else
			led_off(LED_ORANGE);
		if(accel.y<=-3000)
			led_on(LED_BLUE);
		else
			led_off(LED_BLUE);

		DelayMs(1000);
	}
}

