/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include<string.h>
#include"stm32f4xx.h"
#include"system_stm32f4xx.h"
#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


volatile uint32_t ticks;




int main(void)
{
    /* Loop forever */
	LedInit(LED_BLUE);
	SysTick_Config(SystemCoreClock / 1000);
	while(1){
		LedToggle(LED_BLUE);
		SysTickDelayMs(500);

	}
	return 0;
}
